### ISSUE TITLE
Source code original formatting

### ISSUE THREAD

**Issue by shashank-srikant** [jadecxliu/CodeQA#4]
Thanks for this great project.

In the dataset you've released, I notice both `code` and `code.orig` in the different `train`, `dev`, `test` folders are the same, and both contain just the linearized strings of the programs. 

Do you have the programs in their original format? With all the tabs and whitespaces?

Thanks.

**Comment by jadecxliu** [comment]
Hi, we constructed our dataset using the code summarization datasets in [this paper](https://github.com/wasiahmad/NeuralCodeSum/tree/master/data). Unfortunately, as you've noticed, the original formatting with tabs and whitespaces is not included in that source material.

However, to the best of my knowledge, you can access the original programs with proper formatting for Java [here](https://github.com/xing-hu/TL-CodeSum/tree/master) and for Python [here](https://github.com/EdinburghNLP/code-docstring-corpus). I hope you find these resources useful for your needs.

Thanks!

**Comment by hj611** [comment]
> Hi, we constructed our dataset using the code summarization datasets in [this paper](https://github.com/wasiahmad/NeuralCodeSum/tree/master/data). Unfortunately, as you've noticed, the original formatting with tabs and whitespaces is not included in that source material.
> 
> However, to the best of my knowledge, you can access the original programs with proper formatting for Java [here](https://github.com/xing-hu/TL-CodeSum/tree/master) and for Python [here](https://github.com/EdinburghNLP/code-docstring-corpus). I hope you find these resources useful for your needs.
> 
> Thanks!

How can I match source code to QA？
