### ISSUE TITLE
About the version of BLEU

### ISSUE THREAD

**Issue by ANONYEXPCODE** [jadecxliu/CodeQA#7]
Could you please provide the exact version of BLEU used in the evaluation? There are three versions in the source code of [Ahmad et al.] It's quite confusing when we follow your work for new research. It's much better if you can provide the source code of BLEU used in your evaluation.

<img width="521" alt="image" src="https://github.com/user-attachments/assets/23a821a5-223e-4b6e-bf1c-26dab4d1d531">

**Comment by jadecxliu** [comment]
Hi, please refer to https://github.com/jadecxliu/CodeQA/blob/main/codeBERT/code/run.py. The version of BLEU we utilized is clearly indicated there. Thanks!
